version: '3'

services:
  # Django application
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
  # Celery worker
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - .env
  # Redis (result and broker backend)
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
